name: schat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  injectable: ^3.0.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.3.2
  dio: ^5.4.0
  image_picker: ^1.0.7
  json_annotation: ^4.12.0
  file_picker: ^11.0.2
  google_fonts: ^8.1.0
  flutter_bloc: ^9.1.1
  screen_protector: ^1.2.0
  connectivity_plus: ^7.1.1
  fast_contacts: ^5.0.1
  permission_handler: ^12.0.3
  another_flushbar: ^1.12.30
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  web_socket_channel: ^3.0.1
  safe_device: ^1.1.1
  crypto: ^3.0.3
  sms_autofill: ^2.5.0
  firebase_core: ^4.10.0
  share_plus: ^10.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  injectable_generator: ^3.0.2
  freezed: ^3.2.5
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  bloc_test: ^10.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/no_data/
    - assets/home_page/
    - assets/

