name: {{name.titleCase()}}

on:
  push:
    branches:
      - {{branch}}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '{{flutter_version}}'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{open}} secrets.FIREBASE_APP_ID_ANDROID {{close}} --groups "testers"
        env:
          GCP_SA_KEY: ${{open}} secrets.CREDENTIAL_FILE_CONTENT {{close}}
