import 'package:flutter/material.dart';

class CommonIcons {
  CommonIcons._();

  // Asset paths
  static const String logo = 'assets/icons/logo.png';
  static const String defaultAvatar = 'assets/icons/default_avatar.png';
  static const String home = 'assets/home_page/home.png';
  static const String statusIcon = 'assets/home_page/status.png';
  static const String call = 'assets/home_page/call.png';
  static const String newChat = 'assets/home_page/new_chat.png';

  // Material IconData mappings
  static const IconData edit = Icons.edit;
  static const IconData addCall = Icons.add_ic_call;
  static const IconData arrowBack = Icons.arrow_back_ios_new_rounded;
  static const IconData phone = Icons.phone_rounded;
  static const IconData videocam = Icons.videocam_rounded;
  static const IconData chatBubble = Icons.chat_bubble_rounded;
  static const IconData moreHoriz = Icons.more_horiz_rounded;
  static const IconData notifications = Icons.notifications_none_rounded;
  static const IconData lock = Icons.lock_outline_rounded;
  static const IconData history = Icons.history_toggle_off_rounded;
  static const IconData arrowForward = Icons.arrow_forward_ios_rounded;
  static const IconData block = Icons.block_rounded;
  static const IconData report = Icons.report_problem_outlined;
  static const IconData add = Icons.add_rounded;
  static const IconData camera = Icons.camera_alt_rounded;
  static const IconData mic = Icons.mic_rounded;
  static const IconData send = Icons.send_rounded;
  static const IconData check = Icons.check_rounded;
  static const IconData checkCircle = Icons.check_circle_rounded;
  static const IconData done = Icons.done_rounded;
  static const IconData doneAll = Icons.done_all_rounded;
  static const IconData search = Icons.search_rounded;
  static const IconData moreVert = Icons.more_vert_rounded;
  static const IconData close = Icons.close;
  static const IconData delete = Icons.delete;
  static const IconData document = Icons.insert_drive_file;
  static const IconData gallery = Icons.insert_photo;
  static const IconData audio = Icons.headset;
  static const IconData location = Icons.location_pin;
  static const IconData person = Icons.person;
  static const IconData micOff = Icons.mic_off_rounded;
  static const IconData callEnd = Icons.call_end_rounded;
  static const IconData volumeUp = Icons.volume_up_rounded;
  static const IconData volumeDown = Icons.volume_down_rounded;
  static const IconData imageNotSupported = Icons.image_not_supported;
  static const IconData playCircle = Icons.play_circle_fill;
  static const IconData addPhoto = Icons.add_photo_alternate_outlined;
  static const IconData privacy = Icons.privacy_tip_outlined;
  static const IconData help = Icons.help_outline;
  static const IconData lightMode = Icons.light_mode_rounded;
  static const IconData darkMode = Icons.dark_mode_rounded;
  static const IconData personOutline = Icons.person_outline_rounded;
  static const IconData wifi = Icons.wifi_rounded;
  static const IconData wifiOff = Icons.wifi_off_rounded;
  static const IconData logout = Icons.logout_rounded;
  static const IconData grid = Icons.grid_view_rounded;
  static const IconData status = Icons.auto_awesome_mosaic_rounded;

  // Additional Icons used in presentation screens
  static const IconData photoLibrary = Icons.photo_library;
  static const IconData textFields = Icons.text_fields;
  static const IconData cameraAlt = Icons.camera_alt;
  static const IconData privacyTipOutlined = Icons.privacy_tip_outlined;
  static const IconData deleteOutline = Icons.delete_outline;
  static const IconData helpOutline = Icons.help_outline;
  static const IconData settings = Icons.settings;
  static const IconData addPhotoAlternateOutlined = Icons.add_photo_alternate_outlined;
  static const IconData formatSize = Icons.format_size_rounded;
  static const IconData syncIcon = Icons.sync_rounded;
  static const IconData arrowForwardIos = Icons.arrow_forward_ios_rounded;
  static const IconData smsOutlined = Icons.sms_outlined;
  static const IconData chatBubbleOutline = Icons.chat_bubble_outline;
  static const IconData mailOutline = Icons.mail_outline;
  static const IconData shareOutlined = Icons.share_outlined;
  static const IconData contactPhoneOutlined = Icons.contact_phone_outlined;
  static const IconData videocamOff = Icons.videocam_off_rounded;
  static const IconData flipCamera = Icons.flip_camera_ios_rounded;
  static const IconData callReceived = Icons.call_received;
  static const IconData callMade = Icons.call_made;
  static const IconData warning = Icons.warning;
  static const IconData security = Icons.security;
  static const IconData bugReport = Icons.bug_report;
  static const IconData sendRounded = Icons.send_rounded;
  static const IconData chat = Icons.chat_rounded;
  static const IconData myLocation = Icons.my_location;
  static const IconData contacts = Icons.contacts;
  static const IconData videoFile = Icons.video_file;
  static const IconData brokenImage = Icons.broken_image;
  static const IconData photoOutlined = Icons.photo_outlined;
  static const IconData videocamOutlined = Icons.videocam_outlined;
  static const IconData linkOutlined = Icons.link_outlined;
  static const IconData photo = Icons.photo;
  static const IconData link = Icons.link;
  static const IconData errorOutline = Icons.error_outline;
  static const IconData checkCircleOutline = Icons.check_circle_outline;
  static const IconData infoOutline = Icons.info_outline;
  static const IconData downloading = Icons.downloading;
  static const IconData copy = Icons.copy;
  static const IconData reply = Icons.reply;
  static const IconData pin = Icons.pin_drop;
  static const IconData forward = Icons.forward;
  static const IconData selectAll = Icons.select_all;
}
